name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    # Add this permissions block:
    permissions:
      contents: write # Allow write access to repository contents

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate GitHub Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Thigzz # Use your username directly or ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN is needed for fetching contribution data

      # This step might be redundant if EndBug/add-and-commit handles it, but doesn't hurt
      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]" # Use the standard bot name format
          git config user.email "github-actions[bot]@users.noreply.github.com" # Use the standard bot email

      - name: Push the generated SVG
        uses: EndBug/add-and-commit@v9
        with:
          # author_name: github-actions[bot] # Let the action use the git config
          # author_email: github-actions[bot]@users.noreply.github.com # Let the action use the git config
          message: "Generate Contribution Snake" # Commit message
          add: "dist/*.svg" # Path to the generated files
          # GITHUB_TOKEN is implicitly used by EndBug/add-and-commit when needed for push