name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Thigzz
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit and Push SVG
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generate GitHub Contribution Snake"
          git push origin main
