name: Waka Readme Stats

on:
  schedule:
    - cron: '0 0 * * *'  # runs every day at midnight UTC
  workflow_dispatch:

jobs:
  update-waka:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.3.0
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          TIME_RANGE: all_time
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          LANG_COUNT: 6

